//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamCore {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XamCore.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NewPump {
            get {
                return ResourceManager.GetString("NewPump", resourceCulture);
            }
        }
        
        public static string PumpHistory {
            get {
                return ResourceManager.GetString("PumpHistory", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        public static string CreatePumpTitle {
            get {
                return ResourceManager.GetString("CreatePumpTitle", resourceCulture);
            }
        }
        
        public static string CreatePumpHeader {
            get {
                return ResourceManager.GetString("CreatePumpHeader", resourceCulture);
            }
        }
        
        public static string KeyCheckMessage {
            get {
                return ResourceManager.GetString("KeyCheckMessage", resourceCulture);
            }
        }
        
        public static string SettingsExchangeConfiguration {
            get {
                return ResourceManager.GetString("SettingsExchangeConfiguration", resourceCulture);
            }
        }
        
        public static string SettingsNotificationSettings {
            get {
                return ResourceManager.GetString("SettingsNotificationSettings", resourceCulture);
            }
        }
        
        public static string ExchangeLabel {
            get {
                return ResourceManager.GetString("ExchangeLabel", resourceCulture);
            }
        }
        
        public static string SymbolLabel {
            get {
                return ResourceManager.GetString("SymbolLabel", resourceCulture);
            }
        }
        
        public static string SpendLabel {
            get {
                return ResourceManager.GetString("SpendLabel", resourceCulture);
            }
        }
        
        public static string HoldTimeLabel {
            get {
                return ResourceManager.GetString("HoldTimeLabel", resourceCulture);
            }
        }
        
        public static string ApiKeyLabel {
            get {
                return ResourceManager.GetString("ApiKeyLabel", resourceCulture);
            }
        }
        
        public static string ApiSecretLabel {
            get {
                return ResourceManager.GetString("ApiSecretLabel", resourceCulture);
            }
        }
        
        public static string ApiKeyPassphrarseLabel {
            get {
                return ResourceManager.GetString("ApiKeyPassphrarseLabel", resourceCulture);
            }
        }
        
        public static string ExchangeDescription {
            get {
                return ResourceManager.GetString("ExchangeDescription", resourceCulture);
            }
        }
        
        public static string SymbolDescription {
            get {
                return ResourceManager.GetString("SymbolDescription", resourceCulture);
            }
        }
        
        public static string SpendDescription {
            get {
                return ResourceManager.GetString("SpendDescription", resourceCulture);
            }
        }
        
        public static string HoldTimeDescription {
            get {
                return ResourceManager.GetString("HoldTimeDescription", resourceCulture);
            }
        }
        
        public static string ErrorApi {
            get {
                return ResourceManager.GetString("ErrorApi", resourceCulture);
            }
        }
        
        public static string ErrorTimeout {
            get {
                return ResourceManager.GetString("ErrorTimeout", resourceCulture);
            }
        }
        
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
    }
}
